### ISSUE TITLE
Add an option to hide widgets. 

### ISSUE THREAD

**Issue by annikovk** [Anonym-tsk/lovelace-starline-card#2]
In my interface StarLine card consumes 1/4 of the iPad's screen, so some elements are overlapping each other. 
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/12910542/89614151-0e0f1500-d8ae-11ea-90e9-4f065e263730.png">

It would be good to have an ability to hide some of them.

**Comment by Bagunda** [comment]
> 

@annikovk 
Подскажите пожалуйста.
Как установить это?
HACS установлен.
Месяц назад я стал знакомиться с Home Assistant. И многое ещё не понимаю.
Но до этого много лет сидел на OpenHab.

**Comment by Omnividente** [comment]
> > 
> 
> @annikovk Подскажите пожалуйста. Как установить это? HACS установлен. Месяц назад я стал знакомиться с Home Assistant. И многое ещё не понимаю. Но до этого много лет сидел на OpenHab.

Открываете HACS-Пользовательский интерфейс. В поиске вбиваем starline и устанавливаем

**Comment by RomanShamilov** [comment]
Didn't find starline-card.js.
tell me where to get it?

**Comment by Anonym-tsk** [comment]
> tell me where to get it?

https://github.com/Anonym-tsk/lovelace-starline-card/blob/master/dist/starline-card.js

**Comment by Anonym-tsk** [comment]
Try to use `master` version.
I added `info` configuration there.

```yaml
type: 'custom:starline-card'
title: Audi
info:
  - battery
  - ctemp
  - etemp
```

More info in [Readme](https://github.com/Anonym-tsk/lovelace-starline-card/blob/master/README.md#available-configuration-options)
