### ISSUE TITLE
dark_mode no work

### ISSUE THREAD

**Issue by gumileeev** [Anonym-tsk/lovelace-starline-card#3]
- title: Starline
    icon: mdi:car
    
    cards:
    

            - type: 'custom:starline-card'
              title: Mazda
              dark: true
              controls:
                - ign
                - arm
                - horn
              entities:
                alarm: binary_sensor.mazda_3_alarm
                balance: sensor.mazda_3_balance
                battery: sensor.mazda_3_battery
                ctemp: sensor.mazda_3_interior_temperature
                door: binary_sensor.mazda_3_doors
                engine: switch.mazda_3_engine
                etemp: sensor.mazda_3_engine_temperature
                gsm_lvl: sensor.mazda_3_gsm_signal
                hbrake: binary_sensor.mazda_3_hand_brake
                hood: binary_sensor.mazda_3_hood
                horn: switch.mazda_3_horn
                location: device_tracker.mazda_3_location
                out: switch.mazda_3_additional_channel
                security: lock.mazda_3_security
                trunk: binary_sensor.mazda_3_trunk
                webasto: switch.mazda_3_webasto
Screen:
https://skr.sh/sBTKYpD6y8M

**Comment by Anonym-tsk** [comment]
![image](https://user-images.githubusercontent.com/1973755/196429907-f5621252-614e-44cd-87e7-41a0b04fe48c.png)
Dark mode works
