### ISSUE TITLE
Add mileage info

### ISSUE THREAD

**Issue by strannick-ru** [Anonym-tsk/lovelace-starline-card#5]
Hi. Thank you so much for your work.

Can you add the status of the mileage sensor to the info?
And is it possible to make info widgets in two lines?

P.S. actually, I'm not sure if this is a good idea, but right now it looks like this and I would like to get all the information right on the card.

![starline-card](https://github.com/Anonym-tsk/lovelace-starline-card/assets/18719896/b791477a-b6fe-477e-9cbe-12563e19b10f)

**Comment by Anonym-tsk** [comment]
Mileage info added in [Release v1.2.2](https://github.com/Anonym-tsk/lovelace-starline-card/releases/tag/v1.2.2)
