### ISSUE TITLE
Не могу войти.

### ISSUE THREAD

**Issue by kevinblo** [Anonym-tsk/lovelace-starline-card#8]
Старая интеграция слетела. По новой получил API ключ. Но интеграция не может войти, пишет неправильный логин или пароль. После нескольких попыток стал запрашивать капчу. Но ни один код не принимает.

**Comment by Anonym-tsk** [comment]
Это не относится к карточке интерфейса. Пожалуйста, пишите в home-assistant.

**Comment by kevinblo** [comment]
Так ты и там не отвечаешь

**Comment by Anonym-tsk** [comment]
Так я и не отвечаю за разработку home-assistant. Там есть ребята на зарплате
